name: MLProjectTemplate
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - xgboost
  - pip:
    - mlflow==1.8